[project]
name = "prediction-of-preeclampsia"
version = "0.1.0"
description = "Preeclampsia prediction system using ML"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "streamlit==1.36.0",
    "pandas==2.2.2",
    "numpy==1.24.4",
    "scikit-learn==1.2.2",
    "joblib==1.3.2"
]